[phases.setup]
nixPkgs = ["php82", "nodejs-18_x"]

[phases.install]
cmds = [
    "curl -sS https://getcomposer.org/installer | php",
    "mv composer.phar /usr/local/bin/composer",
    "chmod +x /usr/local/bin/composer",
    "/usr/local/bin/composer --version",
    "/usr/local/bin/composer install --no-dev --optimize-autoloader",
    "npm install",
]

[phases.build]
cmds = [
    "php artisan key:generate --force",
    "php artisan storage:link",
    "npm run build",
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
